# Generated by Django 5.2 on 2025-04-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Electronics", "0002_products_image_alter_products_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
